version: '3.4'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: ocm_zookeeper
    restart: always
    environment:
      ZOOKEPER_CLIENT_PORT: 2181
      ZOOKEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    container_name: ocm_kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ocm_kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  node:
    build: ./node
    container_name: ocm_node
    restart: always
    depends_on:
      - kafka
    ports:
      - 9999:9999
    volumes:
      - ./../app:/ocm
    environment:
      KAFKA: 'kafka:9092'
      WS_PORT: 9999

  python:
    build: ./python
    container_name: ocm_python
    restart: always
    depends_on:
      - kafka
    volumes:
      - ./python/app:/ocm
    environment:
      KAFKA: 'kafka:9092'